### PR TITLE
Update Georgian translation.

### PR DESCRIPTION
**Pull request by GEveloper**
Hello,
In 2018 and 2019 I have translated this project into Georgian.
Now improving it to match with updated English version.

See #130

### CODE REVIEW

**Comment by GEveloper** [comment]
I'm not sure why building checks failed.
Does it need to make some modifications?

**Comment by inxomnyaa** [comment]
> 
> 
> I'm not sure why building checks failed.
> Does it need to make some modifications?

Its fine, the code itself isn't fully patched up yet, because the docker image is not fully up to date.

**Review by inxomnyaa — APPROVED** [review]

**Comment by inxomnyaa** [comment]
Thanks alot, i might need some more translations one day, feel free to add them if you got time when that happens - I will merge the PR when i fixed the builds, accepted label is added, enjoy hacktoberfest.

**Comment by GEveloper** [comment]
> 
> 
> Thanks alot, i might need some more translations one day, feel free to add them if you got time when that happens - I will merge the PR when i fixed the builds, accepted label is added, enjoy hacktoberfest.

Ok, no problem. Thank you ❤️

**Pull request merged**
