### PR TITLE
[TASK] Update Spanish translation.

### PR DESCRIPTION
**Pull request by luisAzcuaga**
# Problem

- Spanish translations weren standarized, didn't read natural.
- Also many open exlamation and question marks were missing (those are required in spanish!)

# Solution

- Fixed all those faults 😁 

Happy hacktober fest!

### CODE REVIEW

**Review by inxomnyaa — APPROVED** [review]

**Review by inxomnyaa — CHANGES_REQUESTED** [review]
https://github.com/thebigsmileXD/MagicWE2/blob/e499d8eecc599dc263bc92e2649a033a56066a78/resources/lang/esp.ini#L1
Can you update the date?

**Comment by inxomnyaa** [comment]
Oh also, can you update the missing translations from the https://github.com/thebigsmileXD/MagicWE2/tree/palette-preview branch, with WAILA and Outline?

**Comment by luisAzcuaga** [comment]
Updated the date, also fixed couple of strings more :)

**Comment by luisAzcuaga** [comment]
> Oh also, can you update the missing translations from the https://github.com/thebigsmileXD/MagicWE2/tree/palette-preview branch, with WAILA and Outline?

I don't quite follow, `palette preview` and `outline` are branches,  but what is __WAILA__?

I see all three branches have the same strings, `master`, `palette_preview` and `outline`  🤔

**Comment by inxomnyaa** [comment]
"what am i looking at", returns the block you are facing and the distance to it

**Comment by luisAzcuaga** [comment]
> "what am i looking at", returns the block you are facing and the distance to it

Umm I opened two PR for the changes in both branches, is that what you wanted? 🤔

**Pull request closed without merging**
