### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by orditeck**

### CODE REVIEW

**Comment by inxomnyaa** [comment]
I think this is irrelevant

I can find translations for conserve, preserve, etc, all with the same meaning.

"Keep air" is meant to be "Preserve blocks with type air"

**Comment by orditeck** [comment]
As a native French speaker from Québec, I can assure you that this is relevant. 

"Garder" and "Conserver" have two different meanings. 

When you say that you can find translations _with the same meanings_, may I ask based on what you're arriving to the conclusion that they have the same meaning?

"Garder" can mean "Conserver", **but it can also mean** "Surveiller" (watch). 
And in such a small sentence, right choice of word matters.

"Conserver" is clear, is not to be interpreted based on context and is the right choice to make it obvious for French-speaking people.

That was a rude way to close a PR, asking the question of why I'm suggesting this would have been better IMO. I, however, should have added what I just explained in my original PR, so sorry about that.

**Comment by orditeck** [comment]
> "Keep air" is meant to be "Preserve blocks with type air"

Suggestion: remplace "Keep air" with "Preserve blocks with type air".

"Preserve" is very eloquent: to cause (an object) to remain in its initial condition.

And in French, you could go with Maintenir, Garder, Conserver.
"Conserver" is definitely the right choice though.

**Comment by orditeck** [comment]
And it shouldn't be "Conserver l'air" or "Garder l'air" in French.

It translates to "Keep the air" 🙈

So my PR should be "Conserver le type air [pour les blocs]". The [pour les blocs] could be removed but add rock-solid precision.

**Comment by inxomnyaa** [comment]
> That was a rude way to close a PR

Shit, i am arguing with a france.

**Comment by inxomnyaa** [comment]
Just asking: Are you _that_ bored to write 3 messages for a 1 word commit? You could've fixed or commented on the french language PR instead (#78 #98 #12 #154 #158 #144 ), like literally, there are already enough PR's for that

**Pull request closed without merging**
