### PR TITLE
Fix German semantics for consistency (on top of PR#137)

### PR DESCRIPTION
**Pull request by flechnical**
I took msdeibel's version from PR #137 (3cce7a8b66317ad46f5e3b2d83d969aa0ceadef6) and cleaned up some stuff for consistency
+ changed some formal speech that was overlooked into informal
+ language.name set to German instead of Deutsch

Is there a better way to propose changes to another PR on Github other than make a new PR?

### CODE REVIEW

**Comment by inxomnyaa** [comment]
I am not sure if we should change the formal to informal again

> language.name set to German instead of Deutsch

This is right, i broke my own rule there ^^"

> Is there a better way to propose changes to another PR on Github other than make a new PR?

I guess you could head to the repository of the pull request creator and change stuff on their repository, but i am unsure if that would show in the main repo

**Comment by inxomnyaa** [comment]
> I am not sure if we should change the formal to informal again

My mistake, informal was the way to go

**Comment by inxomnyaa** [comment]
Compare link: https://github.com/msdeibel/MagicWE2/compare/translations...flechnical:patch-1

**Comment by flechnical** [comment]
> > Is there a better way to propose changes to another PR on Github other than make a new PR?
> 
> I guess you could head to the repository of the pull request creator and change stuff on their repository, but i am unsure if that would show in the main repo

Yeah, I guess they would have to merge the changes on their repo and then create another PR here with my changes in their new commit :D (a PRception so to say)

**Comment by inxomnyaa** [comment]
Okay, now with the original PR merged, i think this could be patched on top.

**Comment by inxomnyaa** [comment]
Patched. No idea how to make GH realize this being mergeable, i manually merged it into translations.

**Pull request closed without merging**
