### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
Enjoy!

### CODE REVIEW

**Comment by inxomnyaa** [comment]
Thanks <3

**Comment by Johnmacrocraft** [comment]
No problem 😊 Time flies so fast, it's been a year since I translated this plugin into Korean!

**Comment by Aericio** [comment]
Oh, its hacktoberfest again.

**Comment by inxomnyaa** [comment]
💯% perfect submission, thanks!

**Pull request merged**
